cc_library(
    name = "file_types",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    visibility = ["//zview:__subpackages__"],
    deps = [
        "//zview/common",
        "@tinyply//:tinyply"],
    includes = ["."]
)