language: cpp
os: linux
compiler: gcc
sudo: required
dist: bionic



addons:
  apt:
    packages:
      - cmake

    # coverity_scan:
    #   project:
    #     name: "ohad.menashe/zview"
    #     description: "Zview: Build submitted via Travis CI"
    #   notification_email: ohad.men@gmail.com
    #   build_command_prepend: "cov-configure --comptype gcc --compiler gcc-4.8"
    #   build_command:   "make VERBOSE=1"
    #   branch_pattern: coverity_scan

# before_install:
  # repo for Qt


install:
  - sudo apt-get --yes install qt5-default


script:
  - qmake zview_gui.pro
  - make
