load("//third_party:qt.bzl", "qt_cc_library")
cc_library(
    name = "vp_mat",
    srcs = ["vp_mat.cpp"],
    hdrs = ["vp_mat.h"],
    visibility = ["//zview:__subpackages__"],
    deps = ["@qt//:qt_gui","//zview/common"]
)
# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
